# Generated by Django 6.0.6 on 2026-06-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
