# Generated by Django 6.0.6 on 2026-06-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
