# Generated by Django 6.0.6 on 2026-06-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Shaxs', 'verbose_name_plural': 'Shaxslar'},
        ),
    ]
