# Generated by Django 6.0.6 on 2026-06-24 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Valyuta kodi')),
                ('name', models.CharField(max_length=100, verbose_name='Valyuta nomi')),
                ('symbol', models.CharField(max_length=10, verbose_name='Belgi')),
            ],
            options={
                'verbose_name': 'Valyuta',
                'verbose_name_plural': 'Valyutalar',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_uzs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Kurs (so'mda)")),
                ('date', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_currencies.currency', verbose_name='Valyuta')),
            ],
            options={
                'verbose_name': 'Valyuta kursi',
                'verbose_name_plural': 'Valyuta kurslari',
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
