# Generated by Django 6.0.6 on 2026-06-25 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_accounts', '0003_alter_account_name'),
        ('app_categories', '0001_initial'),
        ('app_currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Daromad'), ('expense', 'Xarajat')], max_length=10, verbose_name='Tranzaksiya turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Summa (so'mda)")),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('date', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='app_accounts.account', verbose_name='Hisob')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_transactions', to='app_categories.category', verbose_name='Kategoriya')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_transactions', to='app_currencies.currency', verbose_name='Valyuta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-date'],
            },
        ),
    ]
