# Generated by Django 6.0.6 on 2026-06-25 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_alter_account_name'),
        ('app_categories', '0001_initial'),
        ('app_currencies', '0001_initial'),
        ('app_transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Daromad'), ('expense', 'Xarajat')], max_length=10, verbose_name='Tranzaksiya turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('frequency', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], max_length=10, verbose_name='Takrorlanish')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('next_run_date', models.DateField(verbose_name='Keyingi bajarilish sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_recurring_transactions', to='app_accounts.account', verbose_name='Hisob')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_recurring_transactions', to='app_categories.category', verbose_name='Kategoriya')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_recurring_transactions', to='app_currencies.currency', verbose_name='Valyuta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recurring_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Takrorlanuvchi tranzaksiya',
                'verbose_name_plural': 'Takrorlanuvchi tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
