# Generated by Django 6.0.6 on 2026-06-25 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, verbose_name='Karta nomi')),
                ('account_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('bank', 'Bank')], max_length=4, verbose_name="To'lov turi")),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balans')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_currencies.currency', verbose_name='Valyuta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Hisob',
                'verbose_name_plural': 'Hisoblar',
            },
        ),
    ]
