# Generated by Django 6.0.6 on 2026-06-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_alter_account_currency_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=244, verbose_name='Hisob nomi'),
        ),
    ]
